name = input('please enter your full name: ')
phoneNumber = input('Please enter your phone number: ')
productName = input('Please enter the item name you would like to purchase: ')
price = float(input('What is the price of the item you would like to purchase: '))
quantity = int(input('Please enter the quantity of the item being purchased: '))
subtotal = (price *quantity)
tax = ((6/100)*subtotal)
total = tax+subtotal
print()
print()
print(name)
print('Phone number: ',phoneNumber)
print('Purchase information:')
print('Product name:',productName,'  Quantity: ',quantity,'  Price: ',price)
print()
print('Subtotal: ',subtotal,'  Tax: ',tax,'   Total: ',total)